import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { Mp3Encoder } from '@breezystack/lamejs';
const source = ts.transpileModule(readFileSync(new URL('../lib/audio.ts', import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const { splitText, shiftPitch, pcm16, encodeWav } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const text = ('Every word should appear in the generated audio. ').repeat(40).trim();
const chunks = splitText(text);
assert.equal(chunks.join(' '), text);
assert.ok(chunks.every(c => c.length <= 180));
assert.throws(() => splitText('x'.repeat(181)), /too long/);
const samples = Float32Array.from({length: 24000}, (_, i) => Math.sin(2 * Math.PI * 440 * i / 24000) * 0.5);
const raised = shiftPitch(samples, 6);
assert.equal(raised.length, Math.floor(24000 / Math.SQRT2));
const crossings = (s) => { let count = 0; for (let i = 1; i < s.length; i++) if (s[i-1] <= 0 && s[i] > 0) count++; return count; };
assert.ok(Math.abs(crossings(raised) / (raised.length / 24000) - 440 * Math.SQRT2) < 3);
const wav = encodeWav(samples, 24000);
assert.equal(Buffer.from(wav.slice(0,4)).toString(), 'RIFF');
const view = new DataView(wav.buffer);
assert.equal(view.getUint32(24, true), 24000);
assert.equal(view.getUint32(40, true), 48000);
assert.deepEqual([...pcm16(new Float32Array([-2, 0, 2]))], [-32768, 0, 32767]);
const encoder = new Mp3Encoder(1, 24000, 128);
const encoded = [encoder.encodeBuffer(pcm16(samples)), encoder.flush()];
assert.ok(encoded.reduce((sum, p) => sum + p.length, 0) > 1000);
console.log('Passed: text coverage, chunk limits, pitch/duration, WAV headers, PCM clipping, MP3 encoding.');
